version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: previousnext/node:10
    working_directory: /data
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-v2-{{ arch }}-{{ checksum "package-lock.json" }}
            - deps-v2-{{ arch }}-
      - run:
          name: Fetch dependencies
          command: npm ci
      - save_cache:
          key: deps-v2-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Build
          command: npm run build
      - run:
          name: Lint
          command: npm run lint
