version: 2.1

orbs:
  slack: circleci/slack@3.4.2

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: previousnext/node:10
    working_directory: /data
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ arch }}-{{ checksum "package-lock.json" }}
            - deps-{{ arch }}-
      - run:
          name: Fetch dependencies
          command: npm ci
      - save_cache:
          key: deps-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: npm run sass
      - run:
          name: Lint
          command: npm run lint
      - slack/notify-on-failure
